"""
Train CorEx and SVM directly from seed_dataset.json — no database writes.

This script:
  1. Reads backend/seed_dataset.json (generated by generate_seed_dataset.py)
  2. Preprocesses each post text in-memory using the same pipeline as the importer
  3. Trains CorEx and saves the model files to backend/models/
  4. Trains SVM using the _seed_cluster_id labels baked into the seed JSON
  5. Exits cleanly — the database is never touched

The fake seed posts never appear in the dashboard. After running this script,
the model .pkl files are updated and any real posts in the DB can be
re-classified via:
    POST /api/admin/pipeline/run-all   body: {"force_retrain": false}

Run from the backend/ directory:
    python scripts/train_from_seed.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_BACKEND = Path(__file__).parent.parent
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

from app import app, ensure_database  # noqa: E402 — Flask context needed for preprocessing imports

SEED_FILE = _BACKEND / "seed_dataset.json"


def _preprocess_texts(raw_texts: list[str]) -> list[str]:
    """Tokenize + clean texts using the same pipeline as the real importer."""
    from preprocessing import preprocess_record

    results = []
    for i, text in enumerate(raw_texts):
        try:
            result = preprocess_record(
                raw_id=f"seed_{i:04d}",
                item={"text": text},
                record_type="post",
            )
            final = result.get("final_tokens") or []
            results.append(" ".join(final) if final else text.lower())
        except Exception as exc:
            print(f"  [warn] preprocessing failed for '{text[:60]}': {exc}")
            results.append(text.lower())
    return results


def main() -> int:
    if not SEED_FILE.exists():
        print(f"Seed file not found: {SEED_FILE}")
        print("Run: python scripts/generate_seed_dataset.py  first.")
        return 1

    with SEED_FILE.open(encoding="utf-8") as f:
        posts = json.load(f)

    print(f"Loaded {len(posts)} seed posts from {SEED_FILE.name}")

    raw_texts = [
        (p.get("text") or p.get("caption") or "").strip()
        for p in posts
    ]
    labels = [
        [p["_seed_cluster_id"]]
        for p in posts
    ]

    # Count per cluster
    from collections import Counter
    dist = Counter(l[0] for l in labels)
    for cid in sorted(dist):
        print(f"  {cid}: {dist[cid]} posts")

    # We need the Flask app context only for preprocessing helpers that may
    # reference app config. Ensure DB exists (read-only — we don't write anything).
    ensure_database()
    with app.app_context():
        print("\nPreprocessing texts...")
        processed_texts = _preprocess_texts(raw_texts)
        non_empty = [t for t in processed_texts if t.strip()]
        print(f"  {len(non_empty)}/{len(processed_texts)} posts produced non-empty tokens")

        # ── CorEx training ────────────────────────────────────────────────────
        print("\nTraining CorEx...")
        from services.corex.topic_modeler import train_corex
        try:
            result = train_corex(processed_texts)
            print(f"  CorEx trained. Coherence: {result['overall_coherence']:.4f}")
            if result.get("low_coherence_topics"):
                print(f"  Low-coherence topics: {result['low_coherence_topics']}")
        except Exception as exc:
            print(f"  [error] CorEx training failed: {exc}")
            return 1

        # ── SVM training ──────────────────────────────────────────────────────
        print("\nTraining SVM...")
        from services.svm.cluster_classifier import train_svm
        try:
            result = train_svm(processed_texts, labels)
            print(f"  SVM trained.")
            print(f"  Corpus size : {result['corpus_size']}")
            print(f"  Best C      : {result['best_C']}")
            print(f"  F1 macro    : {result['f1_macro']:.4f}  (target >= 0.75)")
        except Exception as exc:
            print(f"  [error] SVM training failed: {exc}")
            return 1

    print("\nDone. Model files updated in backend/models/")
    print("Database was NOT modified — no seed posts in the dashboard.")
    print()
    print("Next: re-predict on real posts without retraining:")
    print('  POST /api/admin/pipeline/run-all  body: {"force_retrain": false}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
